apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmarks-service-configmap
data:
  POSTGRES_HOST: bookmarks-service-postgres-svc
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: bookmarksdb
---
apiVersion: v1
kind: Secret
metadata:
  name: bookmarks-service-secrets
type: Opaque
data:
  POSTGRES_USERNAME: c2l2YQ== # siva
  POSTGRES_PASSWORD: c2l2YWxhYnM= # sivalabs
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarks-service-postgres-svc
spec:
  selector:
    app: bookmarks-service-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarks-service-postgres-deployment
spec:
  selector:
    matchLabels:
      app: bookmarks-service-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookmarks-service-postgres-pod
    spec:
      containers:
        - name: postgres
          image: "postgres:12.3"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bookmarks-service-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmarks-service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: bookmarks-service-configmap
                  key: POSTGRES_DATABASE
